spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/poker_dashboard
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  logging:
    level:
      org.flywaydb: DEBUG