ALTER TABLE users
ADD COLUMN email VARCHAR(255) NOT NULL,
ADD COLUMN password_hash VARCHAR(255) NOT NULL,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
ADD CONSTRAINT uq_users_email UNIQUE (email);